In [1]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /opt/conda/lib/python3.11/site-packages (12.0.1)
Requirement already satisfied: numpy>=1.16.6 in /opt/conda/lib/python3.11/site-packages (from pyarrow) (1.24.3)

In [2]:
import numpy as np
import pandas as pd

In [6]:
BASE_DIR = "../../../CNSM_DATA/v2"

# Read Merged Details

In [7]:
df_merged = pd.read_parquet(BASE_DIR + "/cluster/1pod/cluster_1pod_ks_initial/merged/detail.parquet")
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210672 entries, 0 to 210671
Data columns (total 24 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   request_type                 210672 non-null  category
 1   name                         210672 non-null  category
 2   response_time_ms             210672 non-null  int64
 3   response_length              210672 non-null  int64
 4   event_timestamp              210672 non-null  datetime64[ns]
 5   finished_timestamp           210671 non-null  datetime64[ns]
 6   num_of_users                 210672 non-null  int64
 7   timestamp_start              210671 non-null  datetime64[ns]
 8   timestamp_end                210671 non-null  datetime64[ns]
 9   processing_timestamp_start   0 non-null       datetime64[ns]
 10  processing_timestamp_end     0 non-null       datetime64[ns]
 11  binary_timestamp_start       0 non-null       datetime64[ns]
 12  binary_timestamp_end         0 non-null       datetime64[ns]
 13  multi_class_timestamp_start  0 non-null       datetime64[ns]
 14  multi_class_timestamp_end    0 non-null       datetime64[ns]
 15  zero_day_timestamp_start     0 non-null       datetime64[ns]
 16  zero_day_timestamp_end       0 non-null       datetime64[ns]
 17  anomaly_score                210672 non-null  float64
 18  binary_prediction            210672 non-null  category
 19  multi_class_confidence       93076 non-null   float64
 20  multi_class_prediction       93076 non-null   category
 21  total_delay                  210671 non-null  timedelta64[ns]
 22  flow_type                    210672 non-null  category
 23  num_repetition               210672 non-null  category
dtypes: category(6), datetime64[ns](12), float64(2), int64(3), timedelta64[ns](1)
memory usage: 30.1 MB

In [8]:
df_merged.head(1)

,request_type,name,response_time_ms,response_length,event_timestamp,finished_timestamp,num_of_users,timestamp_start,timestamp_end,processing_timestamp_start,...,multi_class_timestamp_end,zero_day_timestamp_start,zero_day_timestamp_end,anomaly_score,binary_prediction,multi_class_confidence,multi_class_prediction,total_delay,flow_type,num_repetition
0,POST,Benign,65,285,2023-05-15 12:07:02.177743,2023-05-15 12:07:02.244895,1,2023-05-15 12:08:41.041600,2023-05-15 12:08:41.100079,NaT,...,NaT,NaT,NaT,0.00012,Attack,0.824742,Benign,0 days 00:00:00.067152,Benign,6

# Read Detail Statistics

In [9]:
df_stat = pd.read_parquet('v2/detail_stat.parquet')
# df_stat = pd.read_csv('v2/detail_stat.csv')
# df_stat_sorting = pd.read_parquet('v2/detail_stat_sorting.parquet')
# df_stat_sorting = pd.read_csv('v2/detail_stat_sorting.csv')
df_stat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36630 entries, 0 to 36629
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   topology                36630 non-null  category
 1   deployment              36630 non-null  category
 2   sorting                 36630 non-null  category
 3   scenario                36630 non-null  category
 4   repetition              36630 non-null  category
 5   flow_type               36630 non-null  category
 6   num_users               36630 non-null  int64
 7   throughput              36630 non-null  float64
 8   response_time_ms_count  36630 non-null  float64
 9   response_time_ms_mean   34378 non-null  float64
 10  response_time_ms_std    34362 non-null  float64
 11  response_time_ms_min    34378 non-null  float64
 12  response_time_ms_25%    34378 non-null  float64
 13  response_time_ms_50%    34378 non-null  float64
 14  response_time_ms_60%    34378 non-null  float64
 15  response_time_ms_70%    34378 non-null  float64
 16  response_time_ms_75%    34378 non-null  float64
 17  response_time_ms_80%    34378 non-null  float64
 18  response_time_ms_90%    34378 non-null  float64
 19  response_time_ms_95%    34378 non-null  float64
 20  response_time_ms_99%    34378 non-null  float64
 21  response_time_ms_max    34378 non-null  float64
dtypes: category(6), float64(15), int64(1)
memory usage: 4.7 MB

In [10]:
df_stat.head(3)

,topology,deployment,sorting,scenario,repetition,flow_type,num_users,throughput,response_time_ms_count,response_time_ms_mean,...,response_time_ms_25%,response_time_ms_50%,response_time_ms_60%,response_time_ms_70%,response_time_ms_75%,response_time_ms_80%,response_time_ms_90%,response_time_ms_95%,response_time_ms_99%,response_time_ms_max
0,cluster,1pod,ks_ks,scale-down,1,Benign,1,17.533333,526.0,53.579848,...,26.0,56.0,64.0,67.0,68.0,69.0,95.0,98.0,102.75,114.0
1,cluster,1pod,ks_ks,scale-down,1,Attack,1,0.000000,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,cluster,1pod,ks_ks,scale-down,1,Zero-Day,1,0.000000,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_resources = pd.read_parquet('v2/resources_stat.parquet')
df_resources.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49764 entries, 0 to 49763
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   topology                    49764 non-null  category
 1   deployment                  49764 non-null  category
 2   sorting                     49764 non-null  category
 3   scenario                    49764 non-null  category
 4   repetition                  49764 non-null  category
 5   num_users                   49764 non-null  int64
 6   container                   49764 non-null  category
 7   cpu_unit                    49764 non-null  object
 8   cpu_avg                     37057 non-null  float64
 9   cpu_min                     37057 non-null  float64
 10  cpu_max                     37057 non-null  float64
 11  cpu_stddev                  37057 non-null  float64
 12  cpu_count                   49764 non-null  int64
 13  mem_unit                    49764 non-null  object
 14  mem_avg                     37059 non-null  float64
 15  mem_min                     37059 non-null  float64
 16  mem_max                     37059 non-null  float64
 17  mem_stddev                  37059 non-null  float64
 18  mem_count                   49764 non-null  int64
 19  traffic_received_unit       49764 non-null  object
 20  traffic_received_avg        49192 non-null  float64
 21  traffic_received_min        49192 non-null  float64
 22  traffic_received_max        49192 non-null  float64
 23  traffic_received_stddev     49192 non-null  float64
 24  traffic_received_count      49764 non-null  int64
 25  traffic_transmitted_unit    49764 non-null  object
 26  traffic_transmitted_avg     49192 non-null  float64
 27  traffic_transmitted_min     49192 non-null  float64
 28  traffic_transmitted_max     49192 non-null  float64
 29  traffic_transmitted_stddev  49192 non-null  float64
 30  traffic_transmitted_count   49764 non-null  int64
dtypes: category(6), float64(16), int64(5), object(4)
memory usage: 9.8+ MB

# Read Aggregated Detail Statistics

In [15]:
df_agg = pd.read_parquet('v2/detail_agg_stat.parquet')
# df_agg = pd.read_csv('v2/detail_agg_stat.csv', index_col=[0,1,2,3,4,5])
# df_agg_sorting = pd.read_parquet('v2/detail_agg_stat_sorting.parquet')
# df_agg_sorting = pd.read_csv('v2/detail_agg_stat_sorting.csv', index_col=[0,1,2,3,4,5])
df_agg.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4158 entries, ('cluster', '1pod', 'ks_ks', 'initial', 1, 'Attack') to ('edge-fog-cloud', '4pod', 'qos_qos', 'scale-up', 100, 'Zero-Day')
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   throughput_mean              4158 non-null   float64
 1   throughput_std               4158 non-null   float64
 2   response_time_ms_count_mean  4158 non-null   float64
 3   response_time_ms_count_std   4158 non-null   float64
 4   response_time_ms_mean_mean   3906 non-null   float64
 5   response_time_ms_mean_std    3906 non-null   float64
 6   response_time_ms_min_mean    3906 non-null   float64
 7   response_time_ms_min_std     3906 non-null   float64
 8   response_time_ms_max_mean    3906 non-null   float64
 9   response_time_ms_max_std     3906 non-null   float64
 10  response_time_ms_25%_mean    3906 non-null   float64
 11  response_time_ms_25%_std     3906 non-null   float64
 12  response_time_ms_50%_mean    3906 non-null   float64
 13  response_time_ms_50%_std     3906 non-null   float64
 14  response_time_ms_60%_mean    3906 non-null   float64
 15  response_time_ms_60%_std     3906 non-null   float64
 16  response_time_ms_70%_mean    3906 non-null   float64
 17  response_time_ms_70%_std     3906 non-null   float64
 18  response_time_ms_75%_mean    3906 non-null   float64
 19  response_time_ms_75%_std     3906 non-null   float64
 20  response_time_ms_80%_mean    3906 non-null   float64
 21  response_time_ms_80%_std     3906 non-null   float64
 22  response_time_ms_90%_mean    3906 non-null   float64
 23  response_time_ms_90%_std     3906 non-null   float64
 24  response_time_ms_95%_mean    3906 non-null   float64
 25  response_time_ms_95%_std     3906 non-null   float64
 26  response_time_ms_99%_mean    3906 non-null   float64
 27  response_time_ms_99%_std     3906 non-null   float64
dtypes: float64(28)
memory usage: 935.6 KB

In [16]:
df_agg.head(3)

                                                          throughput_mean  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack            0.000000
                                               Benign           17.456667
                                               Zero-Day          0.000000

                                                          throughput_std  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack           0.000000
                                               Benign           0.229895
                                               Zero-Day         0.000000

                                                          response_time_ms_count_mean  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                             0.0
                                               Benign                           523.7
                                               Zero-Day                           0.0

                                                          response_time_ms_count_std  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                       0.000000
                                               Benign                       6.896859
                                               Zero-Day                     0.000000

                                                          response_time_ms_mean_mean  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                            NaN
                                               Benign                      53.382213
                                               Zero-Day                          NaN

                                                          response_time_ms_mean_std  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                           NaN
                                               Benign                      0.658897
                                               Zero-Day                         NaN

                                                          response_time_ms_min_mean  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                           NaN
                                               Benign                          23.7
                                               Zero-Day                         NaN

                                                          response_time_ms_min_std  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                          NaN
                                               Benign                     0.483046
                                               Zero-Day                        NaN

                                                          response_time_ms_max_mean  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                           NaN
                                               Benign                         118.2
                                               Zero-Day                         NaN

                                                          response_time_ms_max_std  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                          NaN
                                               Benign                    13.774372
                                               Zero-Day                        NaN

                                                          ...  \
topology deployment sorting scenario num_users flow_type  ...
cluster  1pod       ks_ks   initial  1         Attack     ...
                                               Benign     ...
                                               Zero-Day   ...

                                                          response_time_ms_75%_mean  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                           NaN
                                               Benign                          67.5
                                               Zero-Day                         NaN

                                                          response_time_ms_75%_std  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                          NaN
                                               Benign                     0.527046
                                               Zero-Day                        NaN

                                                          response_time_ms_80%_mean  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                           NaN
                                               Benign                          68.5
                                               Zero-Day                         NaN

                                                          response_time_ms_80%_std  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                          NaN
                                               Benign                     0.527046
                                               Zero-Day                        NaN

                                                          response_time_ms_90%_mean  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                           NaN
                                               Benign                          93.9
                                               Zero-Day                         NaN

                                                          response_time_ms_90%_std  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                          NaN
                                               Benign                      2.13177
                                               Zero-Day                        NaN

                                                          response_time_ms_95%_mean  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                           NaN
                                               Benign                         97.28
                                               Zero-Day                         NaN

                                                          response_time_ms_95%_std  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                          NaN
                                               Benign                     0.806639
                                               Zero-Day                        NaN

                                                          response_time_ms_99%_mean  \
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                           NaN
                                               Benign                       101.147
                                               Zero-Day                         NaN

                                                          response_time_ms_99%_std
topology deployment sorting scenario num_users flow_type
cluster  1pod       ks_ks   initial  1         Attack                          NaN
                                               Benign                     2.018476
                                               Zero-Day                        NaN

[3 rows x 28 columns]

In [17]:
df_agg.loc['cluster', '3pod', 'ks_ks', 'scale-up', 100, :]

,throughput_mean,throughput_std,response_time_ms_count_mean,response_time_ms_count_std,response_time_ms_mean_mean,response_time_ms_mean_std,response_time_ms_min_mean,response_time_ms_min_std,response_time_ms_max_mean,response_time_ms_max_std,...,response_time_ms_75%_mean,response_time_ms_75%_std,response_time_ms_80%_mean,response_time_ms_80%_std,response_time_ms_90%_mean,response_time_ms_90%_std,response_time_ms_95%_mean,response_time_ms_95%_std,response_time_ms_99%_mean,response_time_ms_99%_std
flow_type,,,,,,,,,,,,,,,,,,,,,
Attack,19.71,0.920956,591.3,27.628689,910.649354,49.591244,22.2,0.421637,4028.4,575.158181,...,1211.650,79.794371,1319.26,87.616338,1630.14,100.880008,1971.720,141.444448,2963.725,401.264961
Benign,151.77,3.621181,4553.1,108.635425,540.947347,15.336302,21.2,0.421637,4517.6,527.550356,...,810.300,70.508648,1075.22,55.409221,1691.78,79.628454,2220.535,114.612267,3273.021,411.829698
Zero-Day,2.13,0.329403,63.9,9.882083,1284.106947,157.638858,145.0,46.768936,3726.0,751.069756,...,1719.625,256.186842,1867.90,331.326603,2236.93,344.669636,2636.260,461.648972,3325.010,539.788264

In [18]:
df_resource_agg = pd.read_parquet('v2/resources_agg_stat.parquet')
df_resource_agg.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5676 entries, ('cluster', '1pod', 'ks_ks', 'initial', 1, 'allinoneapi') to ('edge-fog-cloud', '4pod', 'qos_qos', 'scale-up', 100, 'zerodayapi')
Data columns (total 40 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   cpu_count_mean                   5676 non-null   float64
 1   cpu_count_std                    5676 non-null   float64
 2   cpu_avg_mean                     4290 non-null   float64
 3   cpu_avg_std                      4290 non-null   float64
 4   cpu_min_mean                     4290 non-null   float64
 5   cpu_min_std                      4290 non-null   float64
 6   cpu_max_mean                     4290 non-null   float64
 7   cpu_max_std                      4290 non-null   float64
 8   cpu_stddev_mean                  4290 non-null   float64
 9   cpu_stddev_std                   4290 non-null   float64
 10  mem_count_mean                   5676 non-null   float64
 11  mem_count_std                    5676 non-null   float64
 12  mem_avg_mean                     4290 non-null   float64
 13  mem_avg_std                      4290 non-null   float64
 14  mem_min_mean                     4290 non-null   float64
 15  mem_min_std                      4290 non-null   float64
 16  mem_max_mean                     4290 non-null   float64
 17  mem_max_std                      4290 non-null   float64
 18  mem_stddev_mean                  4290 non-null   float64
 19  mem_stddev_std                   4290 non-null   float64
 20  traffic_received_count_mean      5676 non-null   float64
 21  traffic_received_count_std       5676 non-null   float64
 22  traffic_received_avg_mean        5676 non-null   float64
 23  traffic_received_avg_std         5676 non-null   float64
 24  traffic_received_min_mean        5676 non-null   float64
 25  traffic_received_min_std         5676 non-null   float64
 26  traffic_received_max_mean        5676 non-null   float64
 27  traffic_received_max_std         5676 non-null   float64
 28  traffic_received_stddev_mean     5676 non-null   float64
 29  traffic_received_stddev_std      5676 non-null   float64
 30  traffic_transmitted_count_mean   5676 non-null   float64
 31  traffic_transmitted_count_std    5676 non-null   float64
 32  traffic_transmitted_avg_mean     5676 non-null   float64
 33  traffic_transmitted_avg_std      5676 non-null   float64
 34  traffic_transmitted_min_mean     5676 non-null   float64
 35  traffic_transmitted_min_std      5676 non-null   float64
 36  traffic_transmitted_max_mean     5676 non-null   float64
 37  traffic_transmitted_max_std      5676 non-null   float64
 38  traffic_transmitted_stddev_mean  5676 non-null   float64
 39  traffic_transmitted_stddev_std   5676 non-null   float64
dtypes: float64(40)
memory usage: 1.8 MB